spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://47.106.74.177:13306/test_mybatis_plus?allowPublicKeyRetrieval=true&useSSL=false
          username: hd
          password: hd123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://47.106.74.177:13306/test_mybatis_plus2?allowPublicKeyRetrieval=true&useSSL=false
          username: hd
          password: hd123456
          driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  configuration:
    # 日志输出SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper xml文件默认位置：classpath*:/mapper/**/*.xml
#  mapper-locations: classpath*:/mapper/**/*.xml
  # 配置类型别名对应的包
#  type-aliases-package: com.test.mybatisplus.entity
