# 项目端口
server:
  port: 8080
# 项目访问路径
  servlet:
    context-path: /test

spring:
  session:
    store-type: redis
  redis:
    database: 0
    timeout: 3000
    password:
    host: 127.0.0.1   # 单节点模式
    port: 6379
#      sentinel:    # 哨兵模式
#        master: mymaster #主服务器所在集群名称
#        nodes: 192.168.65.60:26379,192.168.65.60:26380,192.168.65.60:26381
#    cluster:  #集群模式
#      nodes: 192.168.50.61:8001,192.168.50.62:8002,192.168.50.63:8003,192.168.50.61:8004,192.168.50.62:8005,192.168.50.63:8006
#    lettuce:
#      pool:
#        max-idle: 50
#        min-idle: 10
#        max-active: 100
#        max-wait: 1000
#    redisson:
#      file: classpath:redisson.yml


