server:
  port: 8081

spring:
  profiles:
    active: prod


person:
  lastName: zhangsan${random.uuid}
  age: ${random.int}
  boss: false
  birth: 2017/12/12
  maps: {k1: v1, k2: v2}
  lists:
    - lisi
    - wangwu
  dog:
    name: ${person.lastName}_小狗
    age: 2

---

server:
  port: 8082

spring:
  profiles: dev


---

server:
  port: 8083

spring:
  profiles: prod