#spring:
#  datasource:
#    username: hd
#    password: hd123456
#    url: jdbc:mysql://47.106.74.177:3306/test_mybatis?allowPublicKeyRetrieval=true&useSSL=true
#    driver-class-name: com.mysql.jdbc.Driver



#master 数据源配置
master:
  datasource:
    username: admin
    password: 123456
    # 默认HikariDataSource数据源没有url属性，有的是jdbcUrl属性
    # 写url会报错：jdbcUrl is required with driverClassName
    jdbc-url: jdbc:mysql://127.0.0.1:3306/test_mybatis?allowPublicKeyRetrieval=true&useSSL=true
    # url: jdbc:mysql://127.0.0.1:3306/test_mybatis?allowPublicKeyRetrieval=true&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver

#slave 数据源配置
slave:
  datasource:
    username: admin
    password: 123456
    jdbc-url: jdbc:mysql://127.0.0.1:3306/test_mybatis2?allowPublicKeyRetrieval=true&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
  #mybatis
#  mybatis.mapper-locations=classpath:/mapper/**/*Mapper.xml

#mybatis:
#  # 指定全局配置文件位置
#  config-location: classpath:mybatis/mybatis-config.xml
#  # 指定sql映射文件位置
#  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com:
      test:
        springboot:
          dao: debug